// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthField } from "./AuthField";

export type AuthPrompt = { prompt_id: string, attempt_id: string, auth_id: string, banner: string | null, message: string | null, error: string | null, fields: Array<AuthField>, };
