// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthChoice } from "./AuthChoice";
import type { AuthFieldKind } from "./AuthFieldKind";

export type AuthField = { name: string, label: string, kind: AuthFieldKind, required: boolean, numeric: boolean, choices: Array<AuthChoice>, };
