// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserMode } from "./BrowserMode";
import type { BrowserPhase } from "./BrowserPhase";
import type { BrowserStage } from "./BrowserStage";

export type BrowserPrompt = { attempt_id: string, transaction_id: string, expected_origin: string, phase: BrowserPhase, mode: BrowserMode, stage: BrowserStage, account: string | null, };
