// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolInfo } from "./ProtocolInfo";

export type Capabilities = { engine_version: string, api_major: number, api_minor: number, protocols: Array<ProtocolInfo>, pkcs11: boolean, totp: boolean, hotp: boolean, stoken: boolean, yubioath: boolean, hpke: boolean, };
