// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CertificatePrompt = { prompt_id: string, attempt_id: string, host: string, port: number, reason: string, details: string, fingerprint: string, changed_pin: boolean, };
