// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { Error } from "./Error";
import type { ServiceStatus } from "./ServiceStatus";

export type DoctorReport = { capabilities: Capabilities | null, engine_error: Error | null, service: ServiceStatus | null, service_error: Error | null, driver_ready: boolean, driver_error: Error | null, };
