// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "invalid_input" | "unsupported_protocol" | "unsupported_authentication" | "engine_unavailable" | "runtime_failure" | "authentication_required" | "authentication_rejected" | "service_unavailable" | "authorization_denied" | "busy" | "conflict" | "not_found" | "corrupt_storage" | "newer_schema" | "keyring_unavailable" | "certificate_rejected" | "cancelled" | "protocol_violation" | "network_failure" | "recovery_required";
