// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * Messages must be application-authored; native/remote payloads are never error details.
 */
export type Error = { code: ErrorCode, message: string, details: string | null, };
