// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkObservation = { interface: string, addresses: Array<string>, dns_servers: Array<string>, search_domains: Array<string>, routes: Array<string>, transport: string, };
