// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CertificatePin } from "./CertificatePin";

export type PinsDocument = { schema_version: number, revision: number, pins: Array<CertificatePin>, };
