// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserMode } from "./BrowserMode";
import type { TokenMode } from "./TokenMode";

export type Profile = { id: string, revision: number, name: string, protocol: string, server: string, username: string | null, auth_group: string | null, gateway: string | null, ca_file: string | null, client_certificate: string | null, client_key: string | null, secondary_certificate: string | null, secondary_key: string | null, proxy: string | null, user_agent: string | null, reported_os: string | null, mtu: number | null, sni: string | null, direct_gateway: boolean, disable_dtls: boolean, disable_ipv6: boolean, browser_mode: BrowserMode, token_mode: TokenMode, reconnect_timeout_secs: number, remember_password: boolean, };
