// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Registration and verified IPC readiness are independent observations.
 */
export type ServiceStatus = { packaged: boolean, registered: boolean, running: boolean, approval_required: boolean, login_registered: boolean, };
