// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type Settings = { theme: Theme, start_at_login: boolean, auto_connect_profile_id: string | null, close_to_tray: boolean, };
