// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./Error";
import type { SettingsDocument } from "./SettingsDocument";

/**
 * Derived readiness is separate from the stored settings document.
 */
export type SettingsRead = { document: SettingsDocument, auto_connect_error: Error | null, };
