// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionState } from "./ConnectionState";
import type { Error } from "./Error";
import type { NetworkObservation } from "./NetworkObservation";
import type { TrafficCounters } from "./TrafficCounters";

export type Snapshot = { service_instance_id: string, sequence: number, state: ConnectionState, profile_id: string | null, profile_name: string | null, attempt_id: string | null, session_id: string | null, started_at: number | null, network: NetworkObservation | null, traffic: TrafficCounters, last_error: Error | null, };
